name: Build and publish to Puppet Forge

on:
 push:
  #tags:
      #- '[0-9]+.[0-9]+.[0-9]+'
  branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF:10}
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.vars.outputs.tag }}
    - name: Build and publish module
      uses: Enucatl/action-forge-publish@master
      env:
       FORGE_API_KEY: ${{ secrets.FORGE_API_KEY }}
       REPOSITORY_URL: https://forgeapi.puppet.com/v3/releases
